### PR TITLE
Add support for MCUboot and enable it for BMS C1

### PR DESCRIPTION
**Pull request by martinjaeger**
As the title suggests, this PR adds support for DFU with MCUboot.

So far only enabled for the BMS C1.

See the docs updates on instructions how to test it.

Depends on https://github.com/ThingSet/thingset-zephyr-sdk/pull/48

### CODE REVIEW

**Review by pasrom — COMMENTED** [review]
The changes look good to me. I'd like to test them on my setup this week. Is that okay with you?

**Comment by martinjaeger** [comment]
Sure. No hurry from my side.

Let me know if everything worked well and if the documentation was sufficient.

**Comment by pasrom** [comment]
I did test it and encountered two problems:

1. `west espressif monitor` does not work anymore from the `app` folder (inside `app/build/app` it works).
2. The update script does not receive the `0x84` after the reboot function is called, because the processor is already rebooting, so https://github.com/ThingSet/thingset-zephyr-sdk/pull/50 should resolve it.

**Comment by martinjaeger** [comment]
> 1. `west espressif monitor` does not work anymore from the `app` folder (inside `app/build/app` it works).

Ah, interesting. I just noticed it doesn't work anymore (but didn't associate it with `sysbuild`) and [updated the documentation](https://github.com/LibreSolar/bms-firmware/commit/d71e544058544348c8799de06f2a8bda8e2bbc98) accordingly. I'm using `picocom` all the time anyway and didn't want to dig deeper why `espressif monitor` stopped working.

**Comment by martinjaeger** [comment]
@pasrom I have updated the commit sha in west.yml to pull in your fixes for 2.

**Review by pasrom — APPROVED** [review]
🚀🎉
Thank you for adding this feature!

**Pull request merged**
