### PR TITLE
BQ769x0-variant with mbed shows wrong current/temperature

### PR DESCRIPTION
**Pull request by xsider**

### CODE REVIEW

**Comment by xsider** [comment]
attached wrong files.

**Comment by martinjaeger** [comment]
If you want to include the vzlogger interface into the master branch and thus make sure that it is kept up to date with the rest of the BMS firmware (incl. migration to Zephyr), feel free to send another PR with those updates. I can also give some guidance on how to make it easy to switch between different configurations (e.g. baud rates) in Zephyr based on overlay files and Kconfig settings.

**Comment by xsider** [comment]
I did not get the UART to work in Zephyr (no easy to use printf available) yet. I tried to use the thingset-serial as base but anyway did not get it to work. So i switched back to mbed for intermediate version. If zephyr-version works also, i will set a pull request for vzlogger interface.

**Comment by martinjaeger** [comment]
Sounds good. Did you also try the develop branch?

Printf in Zephyr goes to the uart specified via `zephyr,console = ...;` in the board `.dts` file, maybe that was an issue.

**Comment by xsider** [comment]
I did not consider the printf/printk function from Zepyhr for that purpose. If i have understood correctly, the printk is intended for debug messages only. It bypass the message directly to uart, no buffering etc. I expect a disturbance of the timing of the application then. For my next hardware project, i need to implement the vzlogger-interface into zephyr. I have some MPPT-2420-HPX-pcbs (i know, HC is the up-to-date design) and i do not want to discard them.

**Pull request closed without merging**
